### ISSUE TITLE
Проблема с зависимостью от Ruby 2.6.0

### ISSUE THREAD

**Issue by Drunik01** [southbridgeio/tdlib-schema#2]
При попытке использовать версию redmine_bots не разрешается зависимость для tdlib_ruby - ему, точнее tdlib_schema нужно ruby 2.6 или выше. У меня redmine 4.0.4 и ruby 2.5.5.
Возможно ли снизить зависимость до этой версии ruby?

**Comment by esuslik** [comment]
у меня такая жэе проблема, есть ли варианты снизить зависимость?

**Comment by reshetov** [comment]
К сожалению зависимость снизить не получиться, начинаются проблемы с zeitwerk.
Могу предложить обновиться до Redmine 4.0.9, он уже поддерживает [Ruby 2.6+](https://github.com/redmine/redmine/blob/4.0.9/Gemfile#L3) и обновление должно быть довольно безопастно.
